# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: We Be Remote
email: weberemote@datamcfly.com
description: > # this means to ignore newlines until "baseurl:"
  Remote Jobs for Hackers &amp; other Superheroes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weberemote.com" # the base hostname & protocol for your site
twitter_username: freekrai
github_username:  freekrai

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
permalink: pretty

github:
  repo: freekrai/weberemote
  branch: gh-pages

gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem